### ISSUE TITLE
Abnormal display of navigation bar 导航栏显示异常

### ISSUE THREAD

**Issue by Jesse205** [zhaobozhen/Anywhere-#162]
## 悬浮球错位，背景为白色

![Screenshot_2023-08-09-18-55-32-261_com.absinthe.anywhere_.jpg](https://github.com/zhaobozhen/Anywhere-/assets/51242302/20b4d48e-c7b4-4af9-b7b5-5d1a505ef4d8)

理想情况：背景与低栏保持一致，且悬浮球位于导航栏之上

## 看不清的导航栏
![Screenshot_2023-08-09-18-55-41-842_com.absinthe.anywhere_.jpg](https://github.com/zhaobozhen/Anywhere-/assets/51242302/60830a06-d9d5-4664-9359-47e769a337a1)

理想情况：导航栏图标应该为黑色

**Comment by zhaobozhen** [comment]
导航栏 Fab 位置错误是 Material 组件和 Insets 库之间搭配的问题，在不修改库的情况下不是很好解决，暂时改为 cradle 模式
