### ISSUE TITLE
显式广播支持

### ISSUE THREAD

**Issue by EZForever** [zhaobozhen/Anywhere-#8]
安卓8.0引入的[广播限制](https://developer.android.google.cn/about/versions/oreo/background?hl=zh-cn#broadcasts)使得静态注册（在`AndroidManifest.xml`中注册）的广播接收器接收不到隐式广播。现版本Anywhere（v2.3.5）的广播卡片只能通过指定可选的包名发送隐式广播，意味着静态注册接收器的APP是接收不到的。

发送显式广播需要在构造Intent时显式指定接收器组件（`Intent.setComponent()`），需要包名和类名。鉴于Activity卡片已经可以指定包名和类名，为广播卡片添加指定类名的功能应该可以参考。

**Comment by kkocdko** [comment]
可以使用shell卡片，使用命令进行广播

**Comment by EZForever** [comment]
Anywhere是以它自己的权限执行shell命令的。在有些ROM中普通APP是没权限用am或pm指令的，例如vivo家的Funtouch OS 9，`am --help`都会报错：`cmd: Failure calling service activity: Failed transaction (2147483646)`。

**Comment by zhaobozhen** [comment]
2.3.7 版本广播卡片增加了类名参数，由于 Play 商店的新政策，暂时无法审核通过，请先到酷安下载。
